// app/constants/commonCharacters.ts v1.2.1

export interface CommonCharacter {
  char: string;
  pinyin: string;
  definition: string;
}

export const COMMON_CHARACTERS: CommonCharacter[] = [
  { char: '一', pinyin: 'yī', definition: 'one' },
  { char: '二', pinyin: 'èr', definition: 'two' },
  { char: '三', pinyin: 'sān', definition: 'three' },
  { char: '人', pinyin: 'rén', definition: 'person' },
  { char: '口', pinyin: 'kǒu', definition: 'mouth' },
  { char: '日', pinyin: 'rì', definition: 'sun, day' },
  { char: '月', pinyin: 'yuè', definition: 'moon, month' },
  { char: '山', pinyin: 'shān', definition: 'mountain' },
  { char: '水', pinyin: 'shuǐ', definition: 'water' },
  { char: '火', pinyin: 'huǒ', definition: 'fire' },
  { char: '木', pinyin: 'mù', definition: 'wood, tree' },
  { char: '天', pinyin: 'tiān', definition: 'sky, day' },
  { char: '地', pinyin: 'dì', definition: 'earth, ground' },
  { char: '你', pinyin: 'nǐ', definition: 'you' },
  { char: '我', pinyin: 'wǒ', definition: 'I, me' },
  { char: '他', pinyin: 'tā', definition: 'he, him' },
  { char: '她', pinyin: 'tā', definition: 'she, her' },
  { char: '它', pinyin: 'tā', definition: 'it' },
  { char: '是', pinyin: 'shì', definition: 'to be, yes' },
  { char: '不', pinyin: 'bù', definition: 'not, no' },
  { char: '了', pinyin: 'le', definition: '(completed action particle)' },
  { char: '在', pinyin: 'zài', definition: 'at, in, on' },
  { char: '有', pinyin: 'yǒu', definition: 'to have, there is' },
  { char: '也', pinyin: 'yě', definition: 'also, too' },
  { char: '和', pinyin: 'hé', definition: 'and, with' },
  { char: '的', pinyin: 'de', definition: '(possessive particle)' },
  { char: '们', pinyin: 'men', definition: '(plural suffix)' },
  { char: '着', pinyin: 'zhe', definition: '(action in progress particle)' },
  { char: '要', pinyin: 'yào', definition: 'to want, to need' },
  { char: '就', pinyin: 'jiù', definition: 'then, precisely' },
  { char: '那', pinyin: 'nà', definition: 'that' },
  { char: '都', pinyin: 'dōu', definition: 'all, both' },
  { char: '这', pinyin: 'zhè', definition: 'this' },
  { char: '以', pinyin: 'yǐ', definition: 'with, by' },
  { char: '个', pinyin: 'gè', definition: '(measure word)' },
  { char: '过', pinyin: 'guò', definition: 'to pass, (past experience particle)' },
  { char: '会', pinyin: 'huì', definition: 'can, will, meeting' },
  { char: '上', pinyin: 'shàng', definition: 'up, on' },
  { char: '下', pinyin: 'xià', definition: 'down, under' },
  { char: '左', pinyin: 'zuǒ', definition: 'left' },
  { char: '右', pinyin: 'yòu', definition: 'right' },
  { char: '中', pinyin: 'zhōng', definition: 'middle, in' },
  { char: '大', pinyin: 'dà', definition: 'big, large' },
  { char: '小', pinyin: 'xiǎo', definition: 'small, little' },
  { char: '多', pinyin: 'duō', definition: 'many, much' },
  { char: '少', pinyin: 'shǎo', definition: 'few, little' },
  { char: '长', pinyin: 'cháng', definition: 'long' },
  { char: '短', pinyin: 'duǎn', definition: 'short' },
  { char: '好', pinyin: 'hǎo', definition: 'good, well' },
  { char: '坏', pinyin: 'huài', definition: 'bad, broken' },
  { char: '新', pinyin: 'xīn', definition: 'new' },
  { char: '旧', pinyin: 'jiù', definition: 'old, used' },
  { char: '前', pinyin: 'qián', definition: 'front, before' },
  { char: '后', pinyin: 'hòu', definition: 'back, after' },
  { char: '里', pinyin: 'lǐ', definition: 'inside' },
  { char: '外', pinyin: 'wài', definition: 'outside' },
  { char: '东', pinyin: 'dōng', definition: 'east' },
  { char: '西', pinyin: 'xī', definition: 'west' },
  { char: '南', pinyin: 'nán', definition: 'south' },
  { char: '北', pinyin: 'běi', definition: 'north' },
  { char: '爱', pinyin: 'ài', definition: 'to love' },
  { char: '八', pinyin: 'bā', definition: 'eight' },
  { char: '爸', pinyin: 'bà', definition: 'dad' },
  { char: '杯', pinyin: 'bēi', definition: 'cup, glass' },
  { char: '京', pinyin: 'jīng', definition: 'capital' },
  { char: '本', pinyin: 'běn', definition: 'root, (measure word for books)' },
  { char: '菜', pinyin: 'cài', definition: 'dish, vegetable' },
  { char: '茶', pinyin: 'chá', definition: 'tea' },
  { char: '吃', pinyin: 'chī', definition: 'to eat' },
  { char: '打', pinyin: 'dǎ', definition: 'to hit, to make (a call)' },
  { char: '点', pinyin: 'diǎn', definition: 'point, o\'clock' },
  { char: '电', pinyin: 'diàn', definition: 'electricity' },
  { char: '读', pinyin: 'dú', definition: 'to read' },
  { char: '儿', pinyin: 'ér', definition: 'son, child' },
  { char: '饭', pinyin: 'fàn', definition: 'rice, meal' },
  { char: '飞', pinyin: 'fēi', definition: 'to fly' },
  { char: '机', pinyin: 'jī', definition: 'machine' },
  { char: '高', pinyin: 'gāo', definition: 'high, tall' },
  { char: '兴', pinyin: 'xìng', definition: 'interest, excitement' },
  { char: '工', pinyin: 'gōng', definition: 'work' },
  { char: '作', pinyin: 'zuò', definition: 'to do, to make' },
  { char: '狗', pinyin: 'gǒu', definition: 'dog' },
  { char: '汉', pinyin: 'hàn', definition: 'Han Chinese' },
  { char: '语', pinyin: 'yǔ', definition: 'language' },
  { char: '喝', pinyin: 'hē', definition: 'to drink' },
  { char: '很', pinyin: 'hěn', definition: 'very' },
  { char: '回', pinyin: 'huí', definition: 'to return' },
  { char: '家', pinyin: 'jiā', definition: 'home, family' },
  { char: '叫', pinyin: 'jiào', definition: 'to be called, to call' },
  { char: '今', pinyin: 'jīn', definition: 'today, present' },
  { char: '九', pinyin: 'jiǔ', definition: 'nine' },
  { char: '开', pinyin: 'kāi', definition: 'to open, to start' },
  { char: '看', pinyin: 'kàn', definition: 'to see, to look' },
  { char: '来', pinyin: 'lái', definition: 'to come' },
  { char: '老', pinyin: 'lǎo', definition: 'old' },
  { char: '师', pinyin: 'shī', definition: 'teacher' },
  { char: '冷', pinyin: 'lěng', definition: 'cold' },
  { char: '零', pinyin: 'líng', definition: 'zero' },
  { char: '六', pinyin: 'liù', definition: 'six' },
  { char: '妈', pinyin: 'mā', definition: 'mom' },
  { char: '吗', pinyin: 'ma', definition: '(question particle)' },
  { char: '买', pinyin: 'mǎi', definition: 'to buy' },
  { char: '猫', pinyin: 'māo', definition: 'cat' },
  { char: '没', pinyin: 'méi', definition: 'not have' },
  { char: '米', pinyin: 'mǐ', definition: 'rice' },
  { char: '名', pinyin: 'míng', definition: 'name' },
  { char: '明', pinyin: 'míng', definition: 'bright, tomorrow' },
  { char: '哪', pinyin: 'nǎ', definition: 'which' },
  { char: '呢', pinyin: 'ne', definition: '(question particle)' },
  { char: '能', pinyin: 'néng', definition: 'can, be able to' },
  { char: '年', pinyin: 'nián', definition: 'year' },
  { char: '女', pinyin: 'nǚ', definition: 'female, woman' },
  { char: '朋', pinyin: 'péng', definition: 'friend' },
  { char: '友', pinyin: 'yǒu', definition: 'friend' },
  { char: '漂', pinyin: 'piào', definition: 'beautiful' },
  { char: '亮', pinyin: 'liàng', definition: 'bright, light' },
  { char: '苹', pinyin: 'píng', definition: 'apple' },
  { char: '果', pinyin: 'guǒ', definition: 'fruit' },
  { char: '七', pinyin: 'qī', definition: 'seven' },
  { char: '钱', pinyin: 'qián', definition: 'money' },
  { char: '请', pinyin: 'qǐng', definition: 'please, to invite' },
  { char: '去', pinyin: 'qù', definition: 'to go' },
  { char: '热', pinyin: 'rè', definition: 'hot' },
  { char: '认', pinyin: 'rèn', definition: 'to recognize' },
  { char: '识', pinyin: 'shi', definition: 'to know' },
  { char: '商', pinyin: 'shāng', definition: 'commerce, business' },
  { char: '店', pinyin: 'diàn', definition: 'shop, store' },
  { char: '谁', pinyin: 'shéi', definition: 'who' },
  { char: '什', pinyin: 'shén', definition: 'what' },
  { char: '么', pinyin: 'me', definition: '(suffix for what, etc.)' },
  { char: '十', pinyin: 'shí', definition: 'ten' },
  { char: '时', pinyin: 'shí', definition: 'time, hour' },
  { char: '候', pinyin: 'hou', definition: 'time, moment' },
  { char: '书', pinyin: 'shū', definition: 'book' },
  { char: '说', pinyin: 'shuō', definition: 'to speak, to say' },
  { char: '四', pinyin: 'sì', definition: 'four' },
  { char: '岁', pinyin: 'suì', definition: 'year (of age)' },
  { char: '同', pinyin: 'tóng', definition: 'same, together' },
  { char: '学', pinyin: 'xué', definition: 'to study, to learn' },
  { char: '喂', pinyin: 'wèi', definition: 'hello (on the phone)' },
  { char: '喜', pinyin: 'xǐ', definition: 'to like' },
  { char: '欢', pinyin: 'huān', definition: 'happy, pleased' },
  { char: '先', pinyin: 'xiān', definition: 'first, before' },
  { char: '生', pinyin: 'shēng', definition: 'to be born, student' },
  { char: '现', pinyin: 'xiàn', definition: 'now, current' },
  { char: '想', pinyin: 'xiǎng', definition: 'to think, to want' },
  { char: '谢', pinyin: 'xiè', definition: 'to thank' },
  { char: '写', pinyin: 'xiě', definition: 'to write' },
  { char: '星', pinyin: 'xīng', definition: 'star' },
  { char: '期', pinyin: 'qī', definition: 'period of time' },
  { char: '医', pinyin: 'yī', definition: 'medical' },
  { char: '院', pinyin: 'yuàn', definition: 'institution, courtyard' },
  { char: '意', pinyin: 'yì', definition: 'meaning, idea' },
  { char: '思', pinyin: 'si', definition: 'to think' },
  { char: '雨', pinyin: 'yǔ', definition: 'rain' },
  { char: '再', pinyin: 'zài', definition: 'again' },
  { char: '见', pinyin: 'jiàn', definition: 'to see' },
  { char: '怎', pinyin: 'zěn', definition: 'how' },
  { char: '样', pinyin: 'yàng', definition: 'manner, appearance' },
  { char: '住', pinyin: 'zhù', definition: 'to live, to stay' },
  { char: '字', pinyin: 'zì', definition: 'character, word' },
  { char: '昨', pinyin: 'zuó', definition: 'yesterday' },
  { char: '坐', pinyin: 'zuò', definition: 'to sit' },
  { char: '做', pinyin: 'zuò', definition: 'to do, to make' },
];
