
// app/constants/dictionaryMeta.ts v1.1.0
// This file contains metadata about the offline dictionary & lexicon.
// It is auto-generated by the build script. Do not edit directly.
export const DICTIONARY_SIZE = 518;
export const LEXICON_SIZE = 9599;
