
// app/scripts/copyHanziData.js v1.1.0
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
const require = createRequire(import.meta.url);

const SOURCE_DIR = path.dirname(require.resolve('hanzi-writer-data/package.json'));
const DEST_DIR = path.resolve(process.cwd(), 'public', 'hanzi-data');

if (!fs.existsSync(DEST_DIR)) {
  fs.mkdirSync(DEST_DIR, { recursive: true });
}

console.log('Starting full offline data copy...');
if (!fs.existsSync(SOURCE_DIR)) {
  console.error('Error: hanzi-writer-data package not found. Please run "npm install".');
  process.exit(1);
}

let files = [];
try {
    files = fs.readdirSync(SOURCE_DIR);
} catch (e) {
    console.error("Failed to read source directory", e);
    process.exit(1);
}

const jsonFiles = files.filter(file => file.endsWith('.json'));
console.log(`Found ${jsonFiles.length} character files. Generating metadata...`);

// --- Auto-generate metadata and character list ---
console.log('Generating lexicon metadata...');

// Create character list
const charList = jsonFiles.map(file => path.basename(file, '.json'));
const charListPath = path.join(DEST_DIR, 'character-list.json');
fs.writeFileSync(charListPath, JSON.stringify(charList));
console.log(`Character list with ${charList.length} items saved to ${charListPath}`);

// Copy JSON files
console.log('Copying character files...');
let copiedCount = 0;
for (const file of jsonFiles) {
  const srcPath = path.join(SOURCE_DIR, file);
  const destPath = path.join(DEST_DIR, file);
  // Only copy if destination doesn't exist or is older (optional optimization, but simple copy is safer for consistency)
  fs.copyFileSync(srcPath, destPath);
  copiedCount++;
}
console.log(`Copied ${copiedCount} character files to ${DEST_DIR}`);

// Update metadata file
const metaFilePath = path.resolve(process.cwd(), 'app', 'constants', 'dictionaryMeta.ts');
const dictSizeMatch = fs.existsSync(metaFilePath) 
    ? fs.readFileSync(metaFilePath, 'utf-8').match(/export const DICTIONARY_SIZE = (\d+);/) 
    : null;
const dictSize = dictSizeMatch ? dictSizeMatch[1] : 518; // Default if not found

const newMetaContent = `// app/constants/dictionaryMeta.ts v1.1.0
// This file contains metadata about the offline dictionary & lexicon.
// It is auto-generated by the build script. Do not edit directly.
export const DICTIONARY_SIZE = ${dictSize};
export const LEXICON_SIZE = ${charList.length};
`;

fs.writeFileSync(metaFilePath, newMetaContent, 'utf-8');
console.log(`Lexicon size (${charList.length}) written to ${metaFilePath}`);
console.log('Build data preparation complete.');
